const products = [
  {
    id: 1,
    name: "Slim Fit Casual Shirt",
    brand: "Roadster",
    category: "Men",
    price: 899,
    originalPrice: 1799,
    rating: 4.2,
    logo: "👔",
  },
  {
    id: 2,
    name: "Printed A-Line Kurta",
    brand: "Biba",
    category: "Women",
    price: 749,
    originalPrice: 1499,
    rating: 4.4,
    logo: "👗",
  },
  {
    id: 3,
    name: "Running Sneakers",
    brand: "Nike",
    category: "Footwear",
    price: 3299,
    originalPrice: 4999,
    rating: 4.6,
    logo: "👟",
  },
  {
    id: 4,
    name: "Slim Fit Stretch Jeans",
    brand: "Levis",
    category: "Men",
    price: 1599,
    originalPrice: 2999,
    rating: 4.3,
    logo: "👖",
  },
  {
    id: 5,
    name: "Floral Maxi Dress",
    brand: "Vero Moda",
    category: "Women",
    price: 1299,
    originalPrice: 2599,
    rating: 4.1,
    logo: "👘",
  },
  {
    id: 6,
    name: "Quilted Bomber Jacket",
    brand: "HRX",
    category: "Men",
    price: 1899,
    originalPrice: 3499,
    rating: 4.0,
    logo: "🧥",
  },
  {
    id: 7,
    name: "Structured Handbag",
    brand: "Caprese",
    category: "Accessories",
    price: 1699,
    originalPrice: 2999,
    rating: 4.5,
    logo: "👜",
  },
  {
    id: 8,
    name: "Chronograph Watch",
    brand: "Fossil",
    category: "Accessories",
    price: 5999,
    originalPrice: 8999,
    rating: 4.7,
    logo: "⌚",
  },
  {
    id: 9,
    name: "Cotton Printed T-Shirt",
    brand: "H&M",
    category: "Kids",
    price: 449,
    originalPrice: 899,
    rating: 4.2,
    logo: "👕",
  },
  {
    id: 10,
    name: "Wayfarer Sunglasses",
    brand: "Ray-Ban",
    category: "Accessories",
    price: 2499,
    originalPrice: 3999,
    rating: 4.6,
    logo: "🕶️",
  },
  {
    id: 11,
    name: "Embroidered Saree",
    brand: "Fabindia",
    category: "Women",
    price: 2199,
    originalPrice: 3999,
    rating: 4.4,
    logo: "🥻",
  },
  {
    id: 12,
    name: "Leather Formal Shoes",
    brand: "Clarks",
    category: "Footwear",
    price: 3799,
    originalPrice: 5999,
    rating: 4.3,
    logo: "👞",
  },
  {
    id: 13,
    name: "Cushioned Sports Socks",
    brand: "Puma",
    category: "Men",
    price: 299,
    originalPrice: 599,
    rating: 4.0,
    logo: "🧦",
  },
  {
    id: 14,
    name: "Denim Dungaree",
    brand: "mothercare",
    category: "Kids",
    price: 999,
    originalPrice: 1799,
    rating: 4.1,
    logo: "🧒",
  },
];

export default products;
